import type { UpgradeTrack } from "@tower-defense/shared";
export declare const app: HTMLDivElement;
export declare function must<T extends HTMLElement>(id: string): T;
export declare const el: {
    menuScreen: HTMLElement;
    gameScreen: HTMLElement;
    menuSeed: HTMLInputElement;
    menuPlayerCount: HTMLSelectElement;
    menuAiPlayers: HTMLInputElement;
    menuPlayerNames: HTMLElement;
    menuMessage: HTMLElement;
    menuSettingsBtn: HTMLButtonElement;
    settingsBtn: HTMLButtonElement;
    menuTourBtn: HTMLButtonElement;
    tourBtn: HTMLButtonElement;
    menuStartBtn: HTMLButtonElement;
    menuRefreshBtn: HTMLButtonElement;
    menuResumeBtn: HTMLButtonElement;
    wavePreview: HTMLElement;
    playerId: HTMLSelectElement;
    x: HTMLInputElement;
    y: HTMLInputElement;
    mode: HTMLSelectElement;
    damageType: HTMLSelectElement;
    playerCards: HTMLElement;
    phaseBanner: HTMLElement;
    phaseLabel: HTMLElement;
    phaseSub: HTMLElement;
    playbackControls: HTMLElement;
    playPauseBtn: HTMLButtonElement;
    shortcutBar: HTMLElement;
    overlay: HTMLElement;
    overlaySummary: HTMLElement;
    overlayScores: HTMLElement;
    rematchBtn: HTMLButtonElement;
    guideOverlay: HTMLElement;
    guideCard: HTMLElement;
    guideTitle: HTMLElement;
    guideBody: HTMLElement;
    guideActionBtn: HTMLButtonElement;
    guideCloseBtn: HTMLButtonElement;
    status: HTMLElement;
    placeTowerBtn: HTMLButtonElement;
    readyBtn: HTMLButtonElement;
    moveTowerBtn: HTMLButtonElement;
    moveTowerCost: HTMLElement;
    upgradeBtns: Record<UpgradeTrack, HTMLButtonElement>;
    upgradeCosts: Record<UpgradeTrack, HTMLElement>;
    waveBanner: HTMLElement;
    turnBanner: HTMLElement;
    demoBtn: HTMLButtonElement;
    feedbackQueue: HTMLElement;
    board: HTMLElement;
    snapshot: HTMLTextAreaElement;
    battlefieldMeta: HTMLElement;
    towerMenu: HTMLElement;
    towerMenuTitle: HTMLElement;
    towerMenuClose: HTMLButtonElement;
    zoomInBtn: HTMLButtonElement;
    zoomOutBtn: HTMLButtonElement;
    zoomFitBtn: HTMLButtonElement;
    mobileMoreBtn: HTMLButtonElement;
    controlPanel: HTMLElement;
};
//# sourceMappingURL=dom.d.ts.map